### PR TITLE
Code style fixes

### LINKED ISSUE #1: Code review
As requested by @daften.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L3
File docblock can be skipped in PSR-4 namespaced classes.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L14
Why use ... as ... ? There's no name collision?

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php
Entire file:
Docblock:
  - add description to class properties.
  - add description to method parameters.
  - add description to return documentation.
  - Use fully qualified classnames for typehinting (e.g. \Composer\Package\PackageInterface instead of PackageInterface.
  - Use string[] instead of array[string] for typehinting an array of items.
  - Max comment length = 80.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L44
Personal preference: Add \Composer\Script\Event as a use statement.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L68
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L89
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L104
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L143
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Handler.php#L171
Return immediately instead of storing it in an unused variable first.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php#L2
File docblock can be skipped in PSR-4 namespaced classes.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php
Entire file:
Docblock:
  - add description to class properties.
  - add description to method parameters.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php#L51
Personal preference: Add \Composer\Script\Event as a use statement.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/src/Plugin.php#L60
Personal preference: Add \Composer\Script\Event as a use statement.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L3
File docblock can be skipped in PSR-4 namespaced classes.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php
Entire file:
Docblock:
  - add description to class properties.
  - add description to return documentation.
  - Max comment length = 80.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L101
Punctuation.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L127
s/composer.json/profile.profile/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L129
No need to redeclare $contents.

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L130
s/composer.json/profile.install/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L130
s/composer.json/profile.info.yml/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L211
s/param $command/param string $command/

https://github.com/digipolisgent/drupal-copy-profile/blob/develop/tests/PluginTest.php#L231
Why not $this->fs->mkdir()?

### PR DESCRIPTION
**Pull request by daften**
Fixes #1

### CODE REVIEW

File: src/Handler.php [hunk 1]
```diff
@@ -1,35 +1,41 @@
...
 use Composer\Config;
 use Composer\IO\IOInterface;
-use Composer\Package\PackageInterface;
-use Symfony\Component\Filesystem\Filesystem as SymfonyFilesystem;
+use Composer\Script\Event;
+use Symfony\Component\Filesystem\Filesystem;
 
+/**
+ * Class Handler for DrupalCopyProfile that will copy the profile being
+ * developed to the correct directory
```
Comment (Jelle-S) [inline src/Handler.php]: Punctuation.

File: src/Handler.php [hunk 2]
```diff
@@ -1,35 +1,41 @@
...
    */
   protected $io;
 
   /**
    * Handler constructor.
    *
-   * @param Composer $composer
-   * @param IOInterface $io
+   * @param \Composer\Composer $composer
+   *   The composer instance for the top-level composer.json file
```
Comment (Jelle-S) [inline src/Handler.php]: Punctuation.

File: src/Handler.php [hunk 3]
```diff
@@ -82,28 +89,26 @@ public function getDrupalCorePackage() {
   /**
    * Retrieve the install profile name.
    *
-   *  @return string
+   * @return string
+   *   The name of the install profile being installed
```
Comment (Jelle-S) [inline src/Handler.php]: Punctuation.

File: src/Handler.php [hunk 4]
```diff
@@ -132,21 +140,25 @@ protected function getExcludes() {
    * Respects 'omit-defaults', and either includes or does not include the
    * default values, as requested.
    *
-   * @return array
+   * @return array[]
```
Comment (Jelle-S) [inline src/Handler.php]: Either array if it's a mixed array or objectType[] if the type of each element in the array is the same (eg: string[]).
Unless this returns an array of arrays, in which case this is fine, although I think just array would suffice in that case to avoid confusion?

**Review by Jelle-S — CHANGES_REQUESTED** [review]

**Comment by Jelle-S** [comment]
Seems like I'm not authorized to approve the codeclimate fail, but we discussed this in person. Better to be clear about what parameters a method gets than to fix the codeclimate error complaining about unused parameters.

**Review by Jelle-S — APPROVED** [review]
